In [20]:
import pandas as pd
import numpy as np
df= pd.DataFrame({
    'Date': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05'],
    'Value': [1200, 1300, np.nan, np.nan, 1600]
    })
df

         Date   Value
0  2023-01-01  1200.0
1  2023-01-02  1300.0
2  2023-01-03     NaN
3  2023-01-04     NaN
4  2023-01-05  1600.0

In [21]:
df["Value"] = df["Value"].interpolate(limit_direction='both')
df

         Date   Value
0  2023-01-01  1200.0
1  2023-01-02  1300.0
2  2023-01-03  1400.0
3  2023-01-04  1500.0
4  2023-01-05  1600.0